Repository padong4284/padong-app, pull requests merged in 2021-04, with the labels that each got.

#317 doc: Change Github username
  README.md
  README_KO.md
Labels: doc

#318 feat: contents pagination
  lib/core/node/chat/chat_room.dart
  lib/core/padong_router.dart
  lib/core/service/padong_fb.dart
  lib/ui/template/board_template.dart
  lib/ui/template/safe_padding_template.dart
  lib/ui/view/chat/chat_room_view.dart
  lib/ui/view/chat/chat_view.dart
  lib/ui/view/deck/board_view.dart
  lib/ui/view/home/home_view.dart
  lib/ui/view/main_view.dart
  lib/ui/view/profile/profile_view.dart
  lib/ui/view/schedule/event_view.dart
  lib/ui/view/schedule/lecture_view.dart
  lib/ui/widget/container/infinity_scroller.dart
  lib/ui/widget/tile/node/post_tile.dart
Labels: feat

#322 feat: Pull to Refersh
  lib/ui/widget/container/infinity_scroller.dart
  lib/ui/widget/container/over_scroll_container.dart
Labels: done, feat

#323 Add a function that making an issue about adding a new university
  ios/Podfile.lock
  lib/core/service/session.dart
  pubspec.yaml
Labels: feat

#330 feat: google maps api key
  android/app/src/main/AndroidManifest.xml
  ios/Runner/AppDelegate.m
  lib/ui/template/map_template.dart
  lib/ui/view/map/map_view.dart
  lib/ui/widget/button/bottom_buttons.dart
  lib/ui/widget/card/service_card.dart
Labels: feat

#335 334 email verification on flutter
  lib/core/node/common/university.dart
  lib/core/node/common/user.dart
  lib/core/service/padong_auth.dart
  lib/core/service/session.dart
  lib/core/shared/anonymity.dart
  lib/core/shared/constants.dart
  lib/core/shared/types.dart
  lib/core/shared/validator.dart
  lib/ui/view/profile/configure_view.dart
  lib/ui/view/sign/sign_up_view.dart
Labels: done

#337 add: google play with app link and app store badge
  README.md
  README_KO.md
  assets/png/google-play-badge.png
  assets/png/xd-image.png
Labels: done

#340 refactor: add license icon and move position
  README.md
  README_KO.md
Labels: done

#331 feat: dialogs
  lib/core/node/chat/chat_room.dart
  lib/core/node/common/user.dart
  lib/core/node/cover/wiki.dart
  lib/core/node/schedule/schedule.dart
  lib/core/padong_router.dart
  lib/core/service/padong_fb.dart
  lib/core/service/session.dart
  lib/core/shared/validator.dart
  lib/ui/template/board_template.dart
  lib/ui/template/map_template.dart
  lib/ui/template/safe_padding_template.dart
  lib/ui/view/chat/chat_room_view.dart
  lib/ui/view/chat/chat_view.dart
  lib/ui/view/chat/chats_view.dart
  lib/ui/view/cover/argue_view.dart
  lib/ui/view/deck/board_view.dart
  lib/ui/view/deck/write_view.dart
  lib/ui/view/profile/configure_view.dart
  lib/ui/view/profile/profile_view.dart
  lib/ui/view/schedule/event_view.dart
  lib/ui/view/schedule/rail_view.dart
  lib/ui/view/sign/base_sign_view.dart
  lib/ui/view/sign/sign_up_view.dart
  lib/ui/widget/button/bottom_buttons.dart
  lib/ui/widget/card/time_table.dart
  lib/ui/widget/card/timeline_card.dart
  lib/ui/widget/dialog/argue_dialog.dart
  lib/ui/widget/dialog/ask_notice_dialog.dart
  lib/ui/widget/dialog/chat_room_dialog.dart
  lib/ui/widget/dialog/forgot_dialog.dart
  lib/ui/widget/dialog/lecture_dialog.dart
  lib/ui/widget/dialog/more_dialog.dart
  lib/ui/widget/dialog/no_univ_dialog.dart
  lib/ui/widget/dialog/user_dialog.dart
  lib/ui/widget/node_base.dart
  lib/ui/widget/tile/node/node_tile.dart
  lib/ui/widget/tile/node/reply_tile.dart
Labels: done, feat

#346 feat: Add IOS notification setting
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
Labels: feat
